-- HCC OS v1.4.0 release manifest.
-- The GitHub repository and raw root are configured only in remote.lua.

return {
    product = "HCC OS",
    version = "1.4.0",
    build = 1400,
    edition = "Tom's Peripherals",
    channel = "stable",
    legacy = "hccos_v1.3.3.lua",
    files = {
        "manifest.lua",
        "version.lua",
        "core/paths.lua",
        "core/logger.lua",
        "core/config.lua",
        "core/remote.lua",
        "core/updater.lua",
        "core/recovery.lua",
        "core/setup.lua",
        "core/legacy_bridge.lua",
        "core/bootstrap.lua",
        "core/runtime.lua",
        "core/app_manager.lua",
        "core/window_manager.lua",
        "core/window_actions.lua",
        "core/input.lua",
        "core/scheduler.lua",
        "core/currency_data.lua",
        "core/image_codec.lua",
        "ui/widgets.lua",
        "ui/gpu_toms.lua",
        "ui/canvas.lua",
        "ui/desktop_view.lua",
        "ui/compositor.lua",
        "ui/icons.lua",
        "ui/desktop.lua",
        "ui/taskbar.lua",
        "ui/start_menu.lua",
        "apps/app_catalog.lua",
        "apps/clock.lua",
        "apps/calendar.lua",
        "apps/radar.lua",
        "apps/server.lua",
        "apps/notepad.lua",
        "apps/files.lua",
        "apps/currency.lua",
        "apps/image.lua",
        "apps/web.lua",
        "apps/inventory.lua",
        "apps/peripherals.lua",
        "apps/network.lua",
        "apps/resource.lua",
        "apps/logs.lua",
        "apps/system.lua",
        "apps/performance.lua",
        "apps/taskmgr.lua",
        "apps/terminal.lua",
        "apps/settings.lua",
        "apps/diagnostics.lua",
        "apps/update_recovery.lua",
        "apps/setup.lua",
        "apps/recovery.lua"
    }
}

