-- HCC OS v1.5.0 release manifest.
-- Storage metadata is consumed by the standalone installer and updater.

return {
    product = "HCC OS",
    version = "1.5.0",
    build = 1500,
    revision = "20260916-8",
    edition = "Tom's Peripherals",
    channel = "stable",
    installedSize = 440000,
    startupSize = 4078,
    maxFileSize = 49152,
    files = {
        "manifest.lua",
        "version.lua",
        "core/paths.lua",
        "core/logger.lua",
        "core/config.lua",
        "core/remote.lua",
        "core/updater.lua",
        "core/recovery.lua",
        "core/setup.lua",
        "core/bootstrap.lua",
        "core/module_loader.lua",
        "core/runtime.lua",
        "core/app_manager.lua",
        "core/app_registry.lua",
        "core/window_manager.lua",
        "core/window_actions.lua",
        "core/input.lua",
        "core/scheduler.lua",
        "core/currency_data.lua",
        "core/image_codec.lua",
        "ui/widgets.lua",
        "ui/gpu_toms.lua",
        "ui/canvas.lua",
        "ui/desktop_view.lua",
        "ui/compositor.lua",
        "ui/cursor.lua",
        "ui/icons.lua",
        "ui/desktop.lua",
        "ui/taskbar.lua",
        "ui/start_menu.lua",
        "lib/hcc/geometry.lua",
        "lib/hcc/tom_gpu.lua",
        "apps/app_catalog.lua",
        "apps/clock/manifest.lua",
        "apps/clock/app.lua",
        "apps/calendar/manifest.lua",
        "apps/calendar/app.lua",
        "apps/radar/manifest.lua",
        "apps/radar/app.lua",
        "apps/server/manifest.lua",
        "apps/server/app.lua",
        "apps/notepad/manifest.lua",
        "apps/notepad/app.lua",
        "apps/files/manifest.lua",
        "apps/files/app.lua",
        "apps/currency/manifest.lua",
        "apps/currency/app.lua",
        "apps/image/manifest.lua",
        "apps/image/app.lua",
        "apps/web/manifest.lua",
        "apps/web/app.lua",
        "apps/inventory/manifest.lua",
        "apps/inventory/app.lua",
        "apps/peripherals/manifest.lua",
        "apps/peripherals/app.lua",
        "apps/network/manifest.lua",
        "apps/network/app.lua",
        "apps/resource/manifest.lua",
        "apps/resource/app.lua",
        "apps/logs/manifest.lua",
        "apps/logs/app.lua",
        "apps/system/manifest.lua",
        "apps/system/app.lua",
        "apps/performance/manifest.lua",
        "apps/performance/app.lua",
        "apps/taskmgr/manifest.lua",
        "apps/taskmgr/app.lua",
        "apps/terminal/manifest.lua",
        "apps/terminal/app.lua",
        "apps/settings/manifest.lua",
        "apps/settings/app.lua",
        "apps/diagnostics/manifest.lua",
        "apps/diagnostics/app.lua",
        "apps/updates/manifest.lua",
        "apps/updates/app.lua",
        "apps/setup/manifest.lua",
        "apps/setup/app.lua"
    }
}

